IWiemTo/Areas/Biologia/Controllers/EditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Reflection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using IWiemTo.Models;
using IWiemTo.Data;


namespace IWiemTo.Areas
{
    [Authorize]
    [Area("Biologia")]

    public class EditController : Controller
    {

        private DbBiolContext _appDBContext;
        private IQuestionsEditor _repo;
        private string AreaName; 

        public EditController(DbBiolContext context, UserManager<ApplicationUser> userManager, IQuestionsEditor questEdytor)
        {
            _appDBContext = context;
            _repo = questEdytor;
            AreaName= typeof(EditorController).GetCustomAttribute<AreaAttribute>().RouteValue;

        }

        public IActionResult Index( int questionID)
        {
            Models.Questions quest = _appDBContext.Questions.Where(item => item.QuestionID == questionID).FirstOrDefault();
            _appDBContext.Entry(quest).Collection(p => p.QuestionCategory).Load();
            _appDBContext.Entry(quest).Collection(p => p.QuestionsImageRel).Load();
            ViewBag.QuestionID = questionID;
            quest.SelectedCategory = quest.QuestionCategory.FirstOrDefault().CategoryID;
            quest.SelectedSubCategory = quest.QuestionCategory.FirstOrDefault().CategorySubID;
            ViewBag.AreaName = AreaName;
            ViewBag.CategoryList = _repo.GetCategories(_appDBContext);            
            ViewBag.SubCategoryList = _repo.GetSubCategoriesByCategoryID(_appDBContext, quest.SelectedCategory);
            ViewBag.TypeQuestion = _repo.LoadTypeOfQuestionContent(_appDBContext);
            ViewBag.LevelKnowledge = _repo.GetLevelKnowledge(_appDBContext);
            return View(quest);
        }

        [HttpPost]
        public ActionResult EditQuestion(Models.Questions quest)
        {
            string previusPage = "Editor";
            Models.Questions record = _appDBContext.Questions.Where(item => item.QuestionID == quest.QuestionID).FirstOrDefault();
            _appDBContext.Entry(record).Collection(p => p.QuestionCategory).Load();
            _appDBContext.Entry(record).Collection(p => p.QuestionsImageRel).Load();
            if (ModelState.IsValid)
            {
                //podstawie pod pola edytowanego rekordu
                record.QuestionText = quest.QuestionText;                
                record.QuestionCategory.FirstOrDefault().CategoryID    = quest.SelectedCategory;
                record.QuestionCategory.FirstOrDefault().CategorySubID = quest.SelectedSubCategory;
                record.QuestionPoints = quest.QuestionPoints;
                record.QuestionSource = quest.QuestionSource;
                record.QuestionExtended = quest.QuestionExtended;
                record.QuestionShortDescribe = quest.QuestionShortDescribe;

                record.QuestionsImageRel.FirstOrDefault().Image = quest.QuestionsImageRel.FirstOrDefault().Image;
                record.QuestionLevelKnowledgeID = quest.QuestionLevelKnowledgeID;
                _appDBContext.SaveChanges();
                
                return RedirectToAction("Index", previusPage);
            }
          
            return RedirectToAction("Index", previusPage);
        }

        public JsonResult GetSubCategoryByCategoryId(string categoryID)
        {
            if (String.IsNullOrEmpty(categoryID))
            {
                throw new ArgumentNullException("categoryId");
            }
            int id = Int32.Parse(categoryID);
            var subCategoryList = _repo.GetSubCategoriesByCategoryID(_appDBContext, id);
            return Json( subCategoryList );
        }

        public IActionResult EditAnswer(int questionID)
        {

            return View();
        }

    }
}

IWiemTo/Areas/Historia/Controllers/EditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Reflection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using IWiemTo.Models;
using IWiemTo.Data;


namespace IWiemTo.Areas.Historia
{
    [Authorize]
    [Area("Historia")]

    public class EditController : Controller
    {

        private DbHistContext _appDBContext;
        private IQuestionsEditor _repo;
        private string AreaName; 

        public EditController(DbHistContext context, UserManager<ApplicationUser> userManager, IQuestionsEditor questEdytor)
        {
            _appDBContext = context;
            _repo = questEdytor;
            AreaName= typeof(EditorController).GetCustomAttribute<AreaAttribute>().RouteValue;

        }

        public IActionResult Index( int questionID)
        {
            Models.Questions quest = _appDBContext.Questions.Where(item => item.QuestionID == questionID).FirstOrDefault();
            _appDBContext.Entry(quest).Collection(p => p.QuestionCategory).Load();
            _appDBContext.Entry(quest).Collection(p => p.QuestionsImageRel).Load();
            ViewBag.QuestionID = questionID;
            quest.SelectedCategory = quest.QuestionCategory.FirstOrDefault().CategoryID;
            quest.SelectedSubCategory = quest.QuestionCategory.FirstOrDefault().CategorySubID;
            ViewBag.AreaName = AreaName;
            ViewBag.CategoryList = _repo.GetCategories(_appDBContext);            
            ViewBag.SubCategoryList = _repo.GetSubCategoriesByCategoryID(_appDBContext, quest.SelectedCategory);
            ViewBag.TypeQuestion = _repo.LoadTypeOfQuestionContent(_appDBContext);
            ViewBag.LevelKnowledge = _repo.GetLevelKnowledge(_appDBContext);
            return View(quest);
        }

        [HttpPost]
        public ActionResult EditQuestion(Models.Questions quest)
        {
            string previusPage = "Editor";
            Models.Questions record = _appDBContext.Questions.Where(item => item.QuestionID == quest.QuestionID).FirstOrDefault();
            _appDBContext.Entry(record).Collection(p => p.QuestionCategory).Load();
            _appDBContext.Entry(record).Collection(p => p.QuestionsImageRel).Load();
            if (ModelState.IsValid)
            {
                //podstawie pod pola edytowanego rekordu
                record.QuestionText = quest.QuestionText;                
                record.QuestionCategory.FirstOrDefault().CategoryID    = quest.SelectedCategory;
                record.QuestionCategory.FirstOrDefault().CategorySubID = quest.SelectedSubCategory;
                record.QuestionPoints = quest.QuestionPoints;
                record.QuestionSource = quest.QuestionSource;
                record.QuestionExtended = quest.QuestionExtended;
                record.QuestionShortDescribe = quest.QuestionShortDescribe;

                record.QuestionsImageRel.FirstOrDefault().Image = quest.QuestionsImageRel.FirstOrDefault().Image;
                record.QuestionLevelKnowledgeID = quest.QuestionLevelKnowledgeID;
                _appDBContext.SaveChanges();
                
                return RedirectToAction("Index", previusPage);
            }
          
            return RedirectToAction("Index", previusPage);
        }

        public JsonResult GetSubCategoryByCategoryId(string categoryID)
        {
            if (String.IsNullOrEmpty(categoryID))
            {
                throw new ArgumentNullException("categoryId");
            }
            int id = Int32.Parse(categoryID);
            var subCategoryList = _repo.GetSubCategoriesByCategoryID(_appDBContext, id);
            return Json( subCategoryList );
        }

    }
}

IWiemTo/Areas/Historia/Views/Edit/Index.cshtml
@model IWiemTo.Models.Questions
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edycja</h2>
<h3><span class="label label-primary">Pytanie nr @ViewBag.QuestionID</span></h3>
<hr />
@{ 
    var image = Model.QuestionsImageRel.FirstOrDefault().Image;
}
<span hidden id="Area">@ViewBag.AreaName</span>


<div class="container">

    <form asp-controller="Edit" asp-action="EditQuestion" method="post">
        @Html.HiddenFor(k => k.QuestionID, new { @Value = ViewBag.QuestionID })
        <div class="row">
            <div class="col-xs-11 col-md-11">
                <div class="form-group">
                    <label for="QuestionTextLabel">Treść pytania</label>
                    <textarea class="form-control" id="QuestionText" name="QuestionText" rows="4" cols="20" asp-for="QuestionText">></textarea>
                </div>
            </div>
            <div class="col-xs-4 col-md-4">
                <div class="form-group">
                    <label id="labelQuestionShortDesc">Krótki opis</label>
                    <textarea class="form-control" id="QuestionShortDescribe" name="QuestionShortDescribe" asp-for="QuestionShortDescribe" rows="1"></textarea>
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="CategoryLabel">Kategoria</label>
                    @Html.DropDownListFor(field => field.SelectedCategory, ViewBag.CategoryList as IEnumerable<SelectListItem>, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.SelectedCategory)
                </div>
            </div>

            <div class="col-xs-5 col-md-5">
                <div class="form-group">
                    <label for="SubCategoryLabel">Podkategoria</label>
                    @Html.DropDownListFor(field => field.SelectedSubCategory, ViewBag.SubCategoryList as IEnumerable<SelectListItem>, new { @class = "form-control" })
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-xs-1 col-md-1">
                <div class="form-group">
                    <label for="SubCategoryLabel">Punktacja</label>
                    <input type="number" class="form-control bfh-number" asp-for="QuestionPoints" min="1" max="100" name="QuestionPoints" placeholder="Wprowadź max ilość pkt. za pytanie">
                </div>
            </div>
            <div class="col-xs-5 col-md-5">
                <label for="SourceLabel">Źródło pytania</label>
                <textarea class="form-control" id="QuestionSource" asp-for="QuestionSource" name="QuestionSource" rows="1" placeholder="Wprowadź nazwę źródła pytania"></textarea>
            </div>
            <div class="col-xs-3 col-md-3">
                <label for="RodzajPytaniaLabel">Rodzaj pytania</label>
                @Html.DropDownListFor(field => field.QuestionExtended, ViewBag.TypeQuestion as IEnumerable<SelectListItem>, new { @class = "form-control" })
            </div>
            <div class="col-xs-2 col-md-2">
                <label for="RodzajPytaniaLabel">Poziom</label>
                @Html.DropDownListFor(field => field.QuestionLevelKnowledgeID, ViewBag.LevelKnowledge as IEnumerable<SelectListItem>, new { @class = "form-control" })
            </div>
        </div>
        
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <input type="file" id="imageLoad1" name="QuestionsImageRel[0].Image" size="60">

                <div class="Image" style="margin-left:10%;">
                    <img style="background-color:red" src=@string.Format("/images/Question/Image/{0}",@image) alt="" />

                </div>
               
                <div class="form-group">
                    <label asp-for="QuestionSource" class="control-label">@Model.QuestionsImageRel.FirstOrDefault().Image</label>
                    <input asp-for="QuestionsImageRel.FirstOrDefault().Image" type="file" class="form-control" />
                    
                </div>

            </div>
        </div>

        <div>
            <input id="submit_btn1" type="submit" class="submit_btn1" value="Zapisz" />
        </div>
    </form>
    <div style="margin-top:10px">
        <a href='javascript:history.go(-1)'>Powrót do listy</a>
    </div>
</div>

@section Scripts{
    <link type="text/css" rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/edit.js" asp-append-version="true"></script>
}