IWiemTo/Areas/Biologia/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using IWiemTo.Data;
using IWiemTo.Models;
using System.Reflection;


namespace IWiemTo.Areas
{
    [Authorize]
    [Area("Biologia")]

    public class EditorController : Controller
    {
        private DbBiolContext _appDBContext;        
        private IQuestionsEditor _repo;
        private readonly UserManager<ApplicationUser> _userManager;
        private List<QuestionsView> quest;

        public EditorController(DbBiolContext  context, UserManager<ApplicationUser> userManager, IQuestionsEditor questEdytor)
        {
            _appDBContext = context;
            _repo = questEdytor;
            _userManager = userManager;
        }


        public IActionResult Index()
        {           
            ViewBag.areaName = typeof(EditorController).GetCustomAttribute<AreaAttribute>().RouteValue;
            return View();
        }

        [HttpPost]
        public IActionResult GetAllQuestionFromDB()
        {
           
            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            // Skiping number of Rows count  
            var start = Request.Form["start"].FirstOrDefault();
            // Paging Length 10,20  
            var length = Request.Form["length"].FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;
            

            // Sort Column Name  
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDir = Request.Form["order[0][dir]"].FirstOrDefault();

            //Sorting    
            if (!(string.IsNullOrEmpty(sortColumn)) && (!string.IsNullOrEmpty(sortColumnDir))) 
            {
                var propertyInfo = typeof(QuestionsView).GetProperty(sortColumn);
                if (sortColumnDir=="asc")
                    quest = _appDBContext.QuestionsView.OrderBy(x =>propertyInfo.GetValue(x,null)).ToList();
                if (sortColumnDir == "desc")
                    quest = _appDBContext.QuestionsView.OrderByDescending(x => propertyInfo.GetValue(x, null)).ToList();
            }


            // Search Value from (Search box)  
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            if (!string.IsNullOrEmpty(searchValue))
            {
                var searchQuery = quest.Where(k => k.QuestionID.ToString() == searchValue ||
                    (k.QuestionShortDescribe!=null && k.QuestionShortDescribe.Contains(searchValue) ) || k.QuestionText.Contains(searchValue)||k.QuestionSource.Contains(searchValue)|| k.SubCategoryName.Contains(searchValue)).ToList();
                quest = searchQuery;
            }
            
            recordsTotal = quest.Count();

            var data = quest.Skip(skip).Take(pageSize).ToList();
            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
        }



        //akcja zwraca słownik typow pytań
        public JsonResult GetDictQuestionType()
        {
            var table = _appDBContext.Dict_QuestionsType.ToList();
            return Json(table);
        }


        public JsonResult GetSubCategoryByCategoryId(string categoryId)
        {
            if (String.IsNullOrEmpty(categoryId))
            {
                throw new ArgumentNullException("categoryId");
            }
            int id = 0;
            bool isValid = Int32.TryParse(categoryId, out id);
            var subCategory = _appDBContext.Dict_SubCategory.AsNoTracking().Where(n => n.CategoryID == id).OrderBy(n => n.SubCategoryName).Select(
                n => new SelectListItem { Value = n.SubCategoryID.ToString(), Text = n.SubCategoryName }).ToList();
            return Json(subCategory);
        }


        //GET Create new question /Editor/Create
        [HttpGet]
        public IActionResult Create(string pageName, string questionTypeName, int questionTypeID, string areaName )
        {                
            ViewData[ "questionType"  ]        =  questionTypeName;
            ViewData[ "questionTypeID"]        =  questionTypeID;
            ViewData[ "Category"      ]        = _repo.GetCategories(_appDBContext);
            ViewData[ "SubCategory"   ]        = _repo.GetSubCategories(_appDBContext);
            ViewData[ "TypeContentOfQuestion"] = _repo.LoadTypeOfQuestionContent(_appDBContext);
            ViewBag.LevelKnowledge             = _repo.GetLevelKnowledge(_appDBContext);
            ViewBag.AreaName                   = typeof(EditorController).GetCustomAttribute<AreaAttribute>().RouteValue;
            return View(pageName);
        }

           
        [HttpPost]
        public ActionResult NewQuestion(Models.Questions  quest)
        {
            
            if (ModelState.IsValid)
            {
                quest.QuestionCreated = DateTime.Now;
                quest.QuestionsChoiceRel.RemoveAll(v => v.ChoiceText == null || string.IsNullOrEmpty(v.ChoiceText));
                quest.QuestionCategory.Add(new Models.QuestionCategory {CategorySubID = quest.SelectedSubCategory, CategoryID = quest.SelectedCategory });                
                _appDBContext.Questions.Add(quest);
                _appDBContext.SaveChanges();               
                return RedirectToAction("Index");
            }

            return View("Index");
        }

        [HttpPost]
        public ActionResult NewOpenQuestion(Models.Questions quest, List<Models.Answers> answer)
        {
            if (ModelState.IsValid)
            {

                quest.QuestionsChoiceRel.RemoveAll(v => v.ChoiceText == null || string.IsNullOrEmpty(v.ChoiceText));
                quest.QuestionCategory.Add(new Models.QuestionCategory { CategorySubID = quest.SelectedSubCategory, CategoryID = quest.SelectedCategory });
                answer.RemoveAll(v => v.Answer == null || string.IsNullOrEmpty(v.Answer));
                _appDBContext.Questions.Add(quest);                
                 _appDBContext.SaveChanges();

                int k = 0;
                foreach (var item in quest.QuestionsChoiceRel)
                {
                    answer[k].QuestionChoiceID = item.QuestionChoiceID;
                    answer[k].QuestionID = item.QuestionID;
                    _appDBContext.Answers.Add(answer[k]);
                    k++;
                }
                _appDBContext.SaveChanges();
                return RedirectToAction("Index");
         

            }

            return View("Index");
        }


    }
}

IWiemTo/Areas/Historia/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using IWiemTo.Data;
using IWiemTo.Models;
using System.Reflection;


namespace IWiemTo.Areas.Historia
{
    [Authorize]
    [Area("Historia")]

    public class EditorController : Controller
    {
        private DbHistContext _appDBContext;        
        private IQuestionsEditor _repo;
        private readonly UserManager<ApplicationUser> _userManager;

        public EditorController(DbHistContext context, UserManager<ApplicationUser> userManager, IQuestionsEditor questEdytor)
        {
            _appDBContext = context;
            _repo = questEdytor;
            _userManager = userManager;
        }


        public IActionResult Index()
        {           
            ViewBag.areaName = typeof(EditorController).GetCustomAttribute<AreaAttribute>().RouteValue;
            return View();
        }

        [HttpPost]
        public IActionResult GetAllQuestionFromDB()
        {

            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            // Skiping number of Rows count  
            var start = Request.Form["start"].FirstOrDefault();
            // Paging Length 10,20  
            var length = Request.Form["length"].FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;
            var quest = _appDBContext.QuestionsView.ToList();
            recordsTotal = quest.Count();

            var data = quest.Skip(skip).Take(pageSize).ToList();
            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
        }



        //akcja zwraca słownik typow pytań
        public JsonResult GetDictQuestionType()
        {
            var table = _appDBContext.Dict_QuestionsType.ToList();
            return Json(table);
        }


        public JsonResult GetSubCategoryByCategoryId(string categoryId)
        {
            if (String.IsNullOrEmpty(categoryId))
            {
                throw new ArgumentNullException("categoryId");
            }
            int id = 0;
            bool isValid = Int32.TryParse(categoryId, out id);
            var subCategory = _appDBContext.Dict_SubCategory.AsNoTracking().Where(n => n.CategoryID == id).OrderBy(n => n.SubCategoryName).Select(
                n => new SelectListItem { Value = n.SubCategoryID.ToString(), Text = n.SubCategoryName }).ToList();
            return Json(subCategory);
        }


        //GET Create new question /Editor/Create
        [HttpGet]
        public IActionResult Create(string pageName, string questionTypeName, int questionTypeID, string areaName )
        {                
            ViewData[ "questionType"  ]        =  questionTypeName;
            ViewData[ "questionTypeID"]        =  questionTypeID;
            ViewData[ "Category"      ]        = _repo.GetCategories(_appDBContext);
            ViewData[ "SubCategory"   ]        = _repo.GetSubCategories(_appDBContext);
            ViewData[ "TypeContentOfQuestion"] = _repo.LoadTypeOfQuestionContent(_appDBContext);
            ViewBag.LevelKnowledge             = _repo.GetLevelKnowledge(_appDBContext);
            ViewBag.AreaName                   = typeof(EditorController).GetCustomAttribute<AreaAttribute>().RouteValue;
            return View(pageName);
        }

           
        [HttpPost]
        public ActionResult NewQuestion(Models.Questions  quest)
        {
            
            if (ModelState.IsValid)
            {

                quest.QuestionsChoiceRel.RemoveAll(v => v.ChoiceText == null || string.IsNullOrEmpty(v.ChoiceText));
                quest.QuestionCategory.Add(new Models.QuestionCategory {CategorySubID = quest.SelectedSubCategory, CategoryID = quest.SelectedCategory });                
                _appDBContext.Questions.Add(quest);
                _appDBContext.SaveChanges();               
                return RedirectToAction("Index");
            }

            return View("Index");
        }

        [HttpPost]
        public ActionResult NewOpenQuestion(Models.Questions quest, List<Models.Answers> answer)
        {
            if (ModelState.IsValid)
            {

                quest.QuestionsChoiceRel.RemoveAll(v => v.ChoiceText == null || string.IsNullOrEmpty(v.ChoiceText));
                quest.QuestionCategory.Add(new Models.QuestionCategory { CategorySubID = quest.SelectedSubCategory, CategoryID = quest.SelectedCategory });
                answer.RemoveAll(v => v.Answer == null || string.IsNullOrEmpty(v.Answer));
                _appDBContext.Questions.Add(quest);                
                 _appDBContext.SaveChanges();

                int k = 0;
                foreach (var item in quest.QuestionsChoiceRel)
                {
                    answer[k].QuestionChoiceID = item.QuestionChoiceID;
                    answer[k].QuestionID = item.QuestionID;
                    _appDBContext.Answers.Add(answer[k]);
                    k++;
                }
                _appDBContext.SaveChanges();
                return RedirectToAction("Index");
         

            }

            return View("Index");
        }


    }
}

IWiemTo/Areas/Biologia/Views/Editor/CreateQuestClose.cshtml
@model IWiemTo.Models.Questions
@using System.Collections
@{
    ViewData["Title"] = "Nowe pytanie";


}

<h3> <span class="label label-primary"> @ViewData["questionType"] </span> </h3>
<link rel="stylesheet" href="~/css/site.css" type="text/css" />

<span hidden id="Area">@ViewBag.AreaName</span>
<div class="container">
    <form asp-action="NewQuestion" asp-controller="Editor" method="post">
        @Html.HiddenFor(m => m.QuestionTypeID, @ViewData["questionTypeID"])
        @Html.HiddenFor(model => model.QuestionCategory, new { })
        <div class="row">
            <br />
            <div class="col-md-12">
                <label for="labelScore">Treść pytania</label>
                <textarea class="form-control" id="QuestionText" name="QuestionText" rows="4" placeholder="Wprowadź treść pytania"></textarea>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-4 col-md-4">
                <label id="labelQuestionShortDescribe">Krótki opis</label>
                <textarea class="form-control" id="QuestionShortDescribe" name="QuestionShortDescribe" placeholder="Wprowadź krótki opis pytania" rows="1"></textarea>
            </div>

            <div class="col-md-4">
                <label for="labelScore">Kategoria</label>
                @Html.DropDownListFor(m => m.SelectedCategory, (IEnumerable<SelectListItem>)ViewData["Category"], new { @class = "form-control" })
            </div>
            <div class="col-md-4">
                <label for="labelScore">Podkategoria</label>
                @Html.DropDownListFor(m => m.SelectedSubCategory, (IEnumerable<SelectListItem>)ViewData["SubCategory"], new { @class = "form-control" })
            </div>
        </div>

        <br />
        <div class="row">
            <div class="col-lg-1 col-md-1 col-xs-1 col-sm-1">
                <label for="labelScore">Punktacja</label>
                <input type="number" class="form-control bfh-number" value="1" min="1" max="100" name="QuestionPoints" placeholder="Wprowadź max ilość pkt. za pytanie">
            </div>
            <div class="col-lg-5 col-md-5 col-xs-5 col-sm-5">
                <label for="labelScore">Źródło pytania</label>
                <textarea class="form-control" id="QuestionSource" name="QuestionSource" rows="1" placeholder="Wprowadź nazwę źródła pytania"></textarea>
            </div>
            <div class="col-lg-3 col-md-3 col-xs-3 col-sm-3">
                <label>Rodzaj  pytania</label>
                @Html.DropDownListFor(m => m.QuestionExtended, (IEnumerable<SelectListItem>)ViewData["TypeContentOfQuestion"], new { @class = "form-control" })
            </div>
            <div class="col-lg-3 col-md-3 col-xs-3 col-sm-3">
                <label>Poziom</label>
                @Html.DropDownListFor(m => m.QuestionLevelKnowledgeID, (IEnumerable<SelectListItem>)ViewBag.LevelKnowledge, new { @class = "form-control" })
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-12">
                <input type="file" id="imageLoad" name="QuestionsImageRel[0].Image" size="60">
            </div>
        </div>

        <br>

        <div class="row">
            <hr>
            <div class="col-md-1 text-left">
                <div class="Choices">
                    <h4> <span class="label label-default"> Warianty odpowiedzi  </span> </h4>
                </div>
            </div>
            <div class="col-md-9 text-left">
                <div class="Choices">

                </div>
            </div>
            <div class="col-md-2 text-left">
                <div class="Choices">
                    <h4> <span class="label label-default">Zaznacz poprawny wariant </span> </h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-1 text-center">
                <label for="labelScore"> A </label>
            </div>
            <div class="col-md-10">
                <textarea class="form-control" id="Choice1" name="QuestionsChoiceRel[0].ChoiceText" cols="30" rows="1" placeholder="wprowadź treść odpowiedź"></textarea>
            </div>
            <div class="col-md-1 text-center">

                <input data-val-required="The isNewlyEnrolled field is required." id="checkbox0" name="QuestionsChoiceRel[0].IsCorect" type="checkbox" value="false" />

            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-1 text-center">
                <label> B </label>
            </div>
            <div class="col-md-10">
                <textarea class="form-control" id="Choice1" name="QuestionsChoiceRel[1].ChoiceText" cols="30" rows="1" placeholder="wprowadź treść odpowiedzi"></textarea>
            </div>
            <div class="col-md-1  text-center">
                <input data-val-required="The isNewlyEnrolled field is required." id="checkbox1" name="QuestionsChoiceRel[1].IsCorect" type="checkbox" value="false" />

            </div>
        </div>

        <br />
        <div class="row">
            <div class="col-md-1 text-center">
                <label> C </label>
            </div>
            <div class="col-md-10">
                <textarea class="form-control" id="Choice1" name="QuestionsChoiceRel[2].ChoiceText" cols="30" rows="1" placeholder="wprowadź treść odpowiedzi"></textarea>
            </div>
            <div class="col-md-1 text-center">
                <input data-val-required="The isNewlyEnrolled field is required." id="checkbox2" name="QuestionsChoiceRel[2].IsCorect" type="checkbox" value="false" />

            </div>
        </div>


        <br />
        <div class="row">
            <div class="col-md-1 text-center">
                <label> D </label>
            </div>
            <div class="col-md-10">
                <textarea class="form-control" id="Choice1" name="QuestionsChoiceRel[3].ChoiceText" cols="30" rows="1" placeholder="wprowadź treść odpowiedzi"></textarea>
            </div>
            <div class="col-md-1 text-center">
                <input data-val-required="The isNewlyEnrolled field is required." id="checkbox3" name="QuestionsChoiceRel[3].IsCorect" type="checkbox" value="false" />

            </div>
        </div>


        <br />
        <div class="row">
            <div class="col-md-1 text-center">
                <label>E </label>
            </div>
            <div class="col-md-10">
                <textarea class="form-control" id="Choice1" name="QuestionsChoiceRel[4].ChoiceText" cols="30" rows="1" placeholder="wprowadź treść odpowiedzi"></textarea>
            </div>
            <div class="col-md-1 text-center">
                <input data-val-required="The isNewlyEnrolled field is required." id="checkbox4" name="QuestionsChoiceRel[4].IsCorect" type="checkbox" value="false" />

            </div>
        </div>

        <br />
        <div>
            <button type="submit" class="submit_btn1"> Dodaj </button>
        </div>
    </form>
</div>

@section Scripts
{
    <script type="text/javascript" src="~/lib/DataTables/datatables.min.js"></script>
    <link type="text/css" href="~/lib/DataTables/datatables.min.css" rel="stylesheet" />
    <script src="~/js/editor.js" asp-append-version="true"></script>
}

IWiemTo/Areas/Biologia/Views/Editor/CreateQuestOpen.cshtml
@model IWiemTo.Models.Questions

@{
    ViewData["Title"] = "Nowe pytanie";


}
<h3> <span class="label label-primary"> @ViewData["questionType"] </span> </h3>

<link rel="stylesheet" href="~/css/site.css" type="text/css" />

<span hidden id="Area">@ViewBag.AreaName</span>
<div class="container">
    <form asp-action="NewOpenQuestion" asp-controller="Editor" method="post">
        @Html.HiddenFor(m => m.QuestionTypeID, @ViewData["questionTypeID"])
        @Html.HiddenFor(model => model.QuestionCategory, new { })

        <div class="row">
            <br />
            <div class="col-md-12">
                <label for="labelScore">Treść pytania</label>
                <textarea class="form-control" id="QuestionText" name="QuestionText" rows="4" placeholder="Wprowadź treść pytania"></textarea>
            </div>
        </div>

        <br />
        <div class="row">
            <div class="col-xs-4 col-md-4">
                <label id="labelQuestionShortDescribe">Krótki opis</label>
                <textarea class="form-control" id="QuestionShortDescribe" name="QuestionShortDescribe" placeholder="Wprowadź krótki opis pytania" rows="1"></textarea>
            </div>
            <div class="col-xs-4 col-md-4">
                <label for="labelScore">Kategoria</label>
                @Html.DropDownListFor(m => m.SelectedCategory, (IEnumerable<SelectListItem>)ViewData["Category"], new { @class = "form-control" })
            </div>
            <div class="col-xs-4 col-md-4">
                <label for="labelScore">Podkategoria</label>
                @Html.DropDownListFor(m => m.SelectedSubCategory, (IEnumerable<SelectListItem>)ViewData["SubCategory"], new { @class = "form-control" })
            </div>
        </div>

        <br />
        <div class="row">
            <div class="col-lg-1 col-md-1 col-xs-1 col-sm-1">
                <label for="labelScore">Punktacja</label>
                <input type="number" class="form-control bfh-number" value="1" min="1" max="100" name="QuestionPoints" placeholder="Wprowadź max ilość pkt. za pytanie">
            </div>
            <div class="col-lg-5 col-md-5 col-xs-5 col-sm-5">
                <label for="labelScore">Źródło pytania</label>
                <textarea class="form-control" id="QuestionSource" name="QuestionSource" rows="1" placeholder="Wprowadź nazwę źródła pytania"></textarea>
            </div>
            <div class="col-lg-3 col-md-3 col-xs-3 col-sm-3">
                <label>Rodzaj  pytania</label>
                @Html.DropDownListFor(m => m.QuestionExtended, (IEnumerable<SelectListItem>)ViewData["TypeContentOfQuestion"], new { @class = "form-control" })
            </div>

            <div class="col-lg-3 col-md-3 col-xs-3 col-sm-3">
                <label>Poziom</label>
                @Html.DropDownListFor(m => m.QuestionLevelKnowledgeID, (IEnumerable<SelectListItem>)ViewBag.LevelKnowledge, new { @class = "form-control" })
            </div>
        </div>


        <br />
        <div class="row">
            <div class="col-md-12">
                <input type="file" id="imageLoad" name="QuestionsImageRel[0].Image" size="60">
            </div>
        </div>

        <br>
        <div class="row">
            <hr>
            <div class="col-md-4 text-left">
                <div class="Choices">
                    <h4> <span class="label label-default"> Podzapytania  </span> </h4>
                </div>
            </div>
            <div class="col-md-4 text-left">
                <div class="Choices">
                    <h4> <span class="label label-default"> Odpowiedzi  </span> </h4>
                </div>
            </div>
            <div class="col-md-4 text-left">
                <div class="Choices">
                    <h4> <span class="label label-default"> Klucze  </span> </h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaSubQuest" name="QuestionsChoiceRel[0].ChoiceText" cols="30" rows="2" placeholder="treść podzapytania nr 1"></textarea>
            </div>
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaAnswer" name="answer[0].Answer" cols="30" rows="2" placeholder="odpowiedź w formie tekstu"></textarea>
            </div>
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaAnswerKey" name="answer[0].SearchVector" cols="30" rows="2" placeholder="klucz odpowiedzi"></textarea>
            </div>
        </div>
        <br>
        <div class="row">

            <div class="col-md-4">
                <textarea class="form-control" id="textAreaSubQuest" name="QuestionsChoiceRel[1].ChoiceText" cols="30" rows="2" placeholder="treść podzapytania nr 2"></textarea>
            </div>
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaAnswer" name="answer[1].Answer" cols="30" rows="2" placeholder="odpowiedź w formie tekstu"></textarea>
            </div>
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaAnswerKey" name="answer[1].SearchVector" cols="30" rows="2" placeholder="klucz odpowiedzi"></textarea>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaSubQuest" name="QuestionsChoiceRel[2].ChoiceText" cols="30" rows="2" placeholder="treść podzapytania nr 3"></textarea>
            </div>
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaAnswer" name="answer[2].Answer" cols="30" rows="2" placeholder="odpowiedź w formie tekstu"></textarea>
            </div>
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaAnswerKey" name="answer[2].SearchVector" cols="30" rows="2" placeholder="klucz odpowiedzi"></textarea>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaSubQuest" name="QuestionsChoiceRel[3].ChoiceText" cols="30" rows="2" placeholder="treść podzapytania nr 4"></textarea>
            </div>
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaAnswer" name="answer[3].Answer" cols="30" rows="2" placeholder="odpowiedź w formie tekstu"></textarea>
            </div>
            <div class="col-md-4">
                <textarea class="form-control" id="textAreaAnswerKey" name="answer[3].SearchVector" cols="30" rows="2" placeholder="klucz odpowiedzi"></textarea>
            </div>
        </div>
        <br />
        <div>
            <button type="submit" class="submit_btn1"> Dodaj </button>
        </div>
    </form>
</div>

@section Scripts
    {
    <script type="text/javascript" src="~/lib/DataTables/datatables.min.js"></script>
    <link type="text/css" href="~/lib/DataTables/datatables.min.css" rel="stylesheet" />
    <script src="~/js/editor.js" asp-append-version="true"></script>
}

IWiemTo/Areas/Biologia/Views/Editor/Index.cshtml
@{
    ViewData["Title"] = "Edytor pytań";
}

<h2>Edytor pytań @ViewBag.areaName</h2>

<div id="container">
    <br />
    <span hidden id="Area">Biologia</span>
    <div class="btn-group">
        <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle">Nowe pytanie <span class="caret"></span></button>
        <ul id="questionTypeDropdown" class="dropdown-menu"></ul>
    </div>
    <br />
    <br />
    <br />
    <button id="btn-show-all-children" type="button">Expand All</button>
    <button id="btn-hide-all-children" type="button">Collapse All</button>
    <hr>
    <div style="width:100%; margin:0 auto;">
        <table id="TableQuestions" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr class="clickable-row">
                    <th>QuestionID</th>
                    <th>QuestionText</th>
                    <th>QuestionShortDescribe</th>
                    <th>QuestionTypeContent</th>
                    <th>CategoryName</th>
                    <th>SubCategoryName</th>
                    <th>QuestionPoints</th>
                    <th>QuestionSource</th>
                    <th>TypeName</th>
                    <th>EditQuest</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/lib/DataTables/datatables.min.js"></script>
    <link type="text/css"  href="~/lib/DataTables/datatables.min.css" rel="stylesheet" />
    <script src="~/js/editor.js" asp-append-version="true"></script>

}